src/Entity/AnnonceSearch.php
<?php

namespace App\Entity;

class AnnonceSearch
{

    /**
     * @var int|null
     */
    private $TarifMin;

    /**
     * @var int|null
     */
    private $TarifMax;

    /**
     * @var int|null
     */
    private $SuperficieMin;

    /**
     * @var int|null
     */
    private $SuperficieMax;

    /**
     * @return int|null
     */
    public function getTarifMin()
    {
        return $this->TarifMin;
    }

    /**
     * @param int|null $TarifMin
     * @return AnnonceSearch
     */
    public function setTarifMin($TarifMin): AnnonceSearch
    {
        $this->TarifMin = $TarifMin;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getTarifMax()
    {
        return $this->TarifMax;
    }

    /**
     * @param int|null $TarifMax
     * @return AnnonceSearch
     */
    public function setTarifMax($TarifMax): AnnonceSearch
    {
        $this->TarifMax = $TarifMax;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getSuperficieMin()
    {
        return $this->SuperficieMin;
    }

    /**
     * @param int|null $SuperficieMin
     * @return AnnonceSearch
     */
    public function setSuperficieMin($SuperficieMin): AnnonceSearch
    {
        $this->SuperficieMin = $SuperficieMin;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getSuperficieMax()
    {
        return $this->SuperficieMax;
    }

    /**
     * @param int|null $SuperficieMax
     * @return AnnonceSearch
     */
    public function setSuperficieMax($SuperficieMax): AnnonceSearch
    {
        $this->SuperficieMax = $SuperficieMax;
        return $this;
    }

}

templates/includes/InfoAnnonce.html.twig
{% for annonce in annonce %}

{% if annonce == false %}
    N/C
{% else %}


    <div class="columns is-centered">

        <div class="columns is-half is-full-touch" style="margin: auto;align-items: center">
            <div class="card-image column is-half" style="align-self: start">
                <div class="media-content column">

                    <div class="column is-vcentered" style="">

                        <h2> <strong class="is-size-3">{{ annonce.titre }}</strong></h2>

                        <time > <i class="tag has-background-info has-text-white is-small">Créée : {{ annonce.datecreation|date('d/m/Y à H:i') }}</i> </time>

                        {% if annonce.publicationauth == null or annonce.publicationauth == false %}
                            <div class="tag is-warning">
                                Annonce non publiée
                            </div>
                            <span class="icon has-text-warning" title="Votre annonce n'est pas publiée">
                                <i class="fas fa-exclamation-triangle"></i>
                            </span>
                        {% elseif annonce.publicationauth == true %}
                            <div class="tag is-success">Annonce publiée le {{ annonce.datepublication|date('d/m/Y à H:i') }}</div>
                        {% endif %}

                        <h3 class="subtitle is-size-6">
                            Par <strong>{{ proprio.raisonsocial }}</strong>
                        </h3>
                    </div>


                </div>

                <div class="columns is-fullwidth is-mobile" style="justify-content: space-around;">
                    <div><h4 class="tag is-info is-size-5">{{ annonce.typelogement }}</h4> </div>
                    <div><h4 class="tag is-info is-size-5">{{ annonce.superficie }}m²</h4> </div>
                    <div><h4 class="tag is-info is-size-5">{{ annonce.tarif }}€ (CC*)</h4> </div>
                </div>

                <figure class="image">
                    {% if annonce.illustrationname %}
                        <img src="{{ vich_uploader_asset(annonce, 'illustration') | imagine_filter('thumb') }}" alt="Placeholder image" style="border-radius: 4px;border: #dfdfdf 1px solid;">
                    {% else %}
                        <img src="{{ asset('build/images/no-image4x3.f917ed4b.jpg') }}" alt="illustration annonce" style="border-radius: 4px;border: #dfdfdf 1px solid;">
                    {% endif %}
                </figure>


            </div>
            <div class="column">

                <div class="content">

                    <p>
                        <h4 class="tag is-info is-size-6">Type de logement</h4> : {{ annonce.typelogement }} <br>

                        <h4 class="tag is-info is-size-6">Loyer</h4> : {{ annonce.tarif }}€ (Charges Comprises) <br>

                        <h4 class="tag is-info is-size-6">Superficie</h4> : {{ annonce.superficie }}m² <br>

                        <h4 class="tag is-info is-size-6">Capacité</h4> : {{ annonce.nombremaxresidents }} locataire(s)<br>

                        <h4 class="tag is-info is-size-6">Adresse</h4> :
                            {% if annonce.adresse is null %}
                                N/C
                            {% else %}
                                {{  annonce.adresse }}
                            {% endif %}<br>

                        <h4 class="tag is-info is-size-6">Code postale</h4> : {{ annonce.cp }} <br>

                        <h4 class="tag is-info is-size-6">Ville</h4> : {{ annonce.ville }} <br>

                        <h4 class="tag is-info is-size-6">Disponible dès le </h4> : {{ annonce.datedisponible|date('d/m/Y') }}<br>


                        <h4 class="tag is-info is-size-6">Détails</h4> :

                            {% if annonce.description is null %}
                                N/C
                            {% else %}
                                <i>
                                {{  annonce.description }}
                                </i>
                            {% endif %}<br>

                    </p>

                </div>

                <div class="columns buttons" style="justify-content: space-between;">

{#                    {% if annonce.publicationauth == true %}#}
{#                        <a class="button is-success is-outlined is-flex column " disabled title="Veuillez retirer la publication de l'annonce avant de la modifier">#}
{#                            <span>Modifier</span>#}
{#                        </a>#}
{#                    {% else %}#}
                        <a href="{{ path('proprio_edit_annonce', {id: annonce.id} ) }}" class="button is-success is-outlined is-flex column">
                            <span>Modifier</span>
                        </a>
{#                    {% endif %}#}

                    {% if annonce.publicationauth == null or annonce.publicationauth == false %}

                        <a href="{{ path('proprio_publication_annonce', {id: annonce.id} ) }}" class="button is-success is-outlined is-flex column">

                            <span>Publier</span>

                            <span class="icon is-small">
                                <i class="fas fa-check"></i>
                            </span>

                        </a>

                    {% else %}

                        <a href="{{ path('proprio_publication_annonce', {id: annonce.id} ) }}" class="button is-warning is-outlined is-flex column">

                            <span>Retirer la publication</span>

                            <span class="icon is-small">
                                <i class="fas fa-times"></i>
                            </span>

                        </a>

                    {% endif %}

                        <a href="{{ path('proprio_delete_annonce', {id: annonce.id} ) }}" class="button is-danger is-outlined is-flex column">

                            <span>Supprimer</span>

                            <span class="icon is-small">
                                <i class="fas fa-times"></i>
                            </span>
                        </a>



                </div>



            </div>
        </div>
        </div>

    <hr style="border:rgba(0,0,0,0.1) 1px solid">







{% endif %}

{% endfor %}

templates/includes/InfoNomade.html.twig
{% for nomade in nomades %}
    {# @var record \App\Entity\Nomade #}





                        <tr>

                            <td>{{ nomade.nom }}</td>

                            <td>{{ nomade.prenom }}</td>

                            <td>{{ nomade.email }}</td>

                            <td>{{ nomade.telephone }}</td>

                            <td>
                                {% if nomade.datenaissance == null %}
                                        N/C
                                {% else %}
{#                                        {{ nomade.datenaissance }}#}
                                    {{ nomade.datenaissance|date("d/m/Y") }}
                                {% endif %}
                            </td>

                            <td>
                                {% if nomade.adresse == null %}
                                        N/C
                                {% else %}
                                        {{ nomade.adresse }}
                                {% endif %}
                            </td>

                            <td>
                                {% if nomade.cp == null %}
                                        N/C
                                {% else %}
                                        {{ nomade.cp }}
                                {% endif %}
                            </td>

                            <td>
                                {% if nomade.ville == null %}
                                        N/C
                                {% else %}
                                        {{ nomade.ville }}
                                {% endif %}
                            </td>

                            <td>
                                {% if nomade.statut == null %}
                                        N/C
                                {% else %}
                                        {{ nomade.statut }}
                                {% endif %}
                            </td>

                            <td>
                                {% if nomade.typesejour == null %}
                                        N/C
                                {% else %}
                                        {{ nomade.typesejour }}
                                {% endif %}
                            </td>

                            <td>
                                {% if nomade.datecreationcompte == null %}
                                        N/C
                                {% else %}
                                    {{ nomade.datecreationcompte|date("d/m/Y") }}
                                {% endif %}

                            </td>
                            <td>
                                <a href="{{ path('admin_gestion_nomade', {id: nomade.id}) }}" class="button is-primary has-text-white is-small">Gérer
                                </a>
                            </td>

                        </tr>





{% endfor %}

templates/includes/InfoProprio.html.twig
{% for proprietaire in proprietaires %}
    {# @var record \App\Entity\Proprietaire #}






            <tr>

                <td>{{ proprietaire.raisonsocial }}</td>

{#                <td>{{ proprietaire.prenom }}</td>#}

                <td>{{ proprietaire.email }}</td>

                <td>{{ proprietaire.telephone }}</td>

{#                <td>#}
{#                    {% if proprietaire.datenaissance == null %}#}
{#                        N/C#}
{#                    {% else %}#}
{#                        {{ proprietaire.datenaissance|date("d/m/Y") }}#}
{#                    {% endif %}#}
{#                </td>#}

                <td>
                    {% if proprietaire.adresse == null %}
                        N/C
                    {% else %}
                        {{ proprietaire.adresse }}
                    {% endif %}
                </td>

                <td>
                    {% if proprietaire.cp == null %}
                        N/C
                    {% else %}
                        {{ proprietaire.cp }}
                    {% endif %}
                </td>

                <td>
                    {% if proprietaire.ville == null %}
                        N/C
                    {% else %}
                        {{ proprietaire.ville }}
                    {% endif %}
                </td>

                <td>
                    {% if proprietaire.statut == null %}
                        N/C
                    {% else %}
                        {{ proprietaire.statut }}
                    {% endif %}
                </td>

{#                <td>#}
{#                    {% if proprietaire.typesejour == null %}#}
{#                        N/C#}
{#                    {% else %}#}
{#                        {{ proprietaire.typesejour }}#}
{#                    {% endif %}#}
{#                </td>#}

                <td>
                    {% if proprietaire.datecreationcompte == null %}
                        N/C
                    {% else %}
                        {{ proprietaire.datecreationcompte|date("d/m/Y") }}
                    {% endif %}
                </td>

                <td>
                    {% if proprietaire.refus == 2 %}
                        <div class="tag is-danger">Refusé</div>
                    {% elseif proprietaire.refus == 1 %}
                        <div class="tag is-success">Validé</div>
                    {% else %}
                        <div class="tag is-warning">En attente</div>
                    {% endif %}
                </td>

                <td>
                    <a href="{{ path('admin_gestion_proprietaire', {id: proprietaire.id}) }}" class="button is-info has-text-white is-small">Gérer
                    </a>
                </td>

            </tr>




{% endfor %}

templates/includes/add_photo_form.html.twig
<div class="field">

    <label class="label">Photo de profile</label>

    {% if nomade.photoprofile is null %}

        <div class="column is-flex" style="justify-content: center;">


                <figure class="image is-256x256">
                    <img src="https://bulma.io/images/placeholders/128x128.png">
                </figure>


        </div>


    {% else %}



        <div class="column is-flex" style="justify-content: center;">
            <figure class="image is-256x256">
                <img src="{{ asset('/uploads/photos_nomades/' ~ nomade.photoprofile) }}" alt="Photo de profile" style="width: 256px;height: 256px">
            </figure>

            {% if nomade.photoprofile is not null %}

                <a href="{{ path('nomade_remove_picture') }}" class="delete"></a>

            {% endif %}

        </div>

    {% endif %}

<div class="column">
    {{ form_row(nomadeForm.photo_profile) }}
</div>


    {#{% if nomade.photoprofile is null %}
    <div class="column">
        {{ form_row(nomadeForm.photo_profile) }}
    </div>
    {% else %}
        {{ form_row(nomadeForm.photo_profile, {'type' : 'hidden'}) }}
    {% endif %}#}

</div>

templates/includes/add_photo_nomade_form.html.twig
<div class="field">
    {#
        <label class="label">Photo de profile</label>

        {% if nomade.photoprofile is null %}

            <div class="column is-flex" style="justify-content: center;">


                <figure class="image is-256x256">
                    <img src="https://bulma.io/images/placeholders/128x128.png">
                </figure>


            </div>


        {% else %}



            <div class="column is-flex" style="justify-content: center;">
                <figure class="image is-256x256">
                    <img src="{{ asset('/uploads/photos_nomades/' ~ nomade.photoprofile) }}" alt="Photo de profile" style="width: 256px;height: 256px">
                </figure>

                {% if nomade.photoprofile is not null %}

                    <a href="{{ path('nomade_remove_picture') }}" class="delete"></a>

                {% endif %}

            </div>

        {% endif %}#}

    <div class="column">
        {{ form_row(nomadeForm.photo_nomade) }}
    </div>


    {#{% if nomade.photoprofile is null %}
    <div class="column">
        {{ form_row(nomadeForm.photo_profile) }}
    </div>
    {% else %}
        {{ form_row(nomadeForm.photo_profile, {'type' : 'hidden'}) }}
    {% endif %}#}

</div>

templates/includes/annonce_search_form.html.twig
<div style="justify-content: space-between;display: flex">

    <a class="button is-primary is-outlined" href="{{ path('nomade_presentation') }}"> <strong>Présentation</strong></a>

    <div>
        <div class="button" id="dropdown-filtres">
            <span>Filtres</span>
            <span class="icon is-small">
            <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
        </div>
{#        {% set favCount = 0 %}#}
{#        {% for annonce in nomade.favori %}#}
{#            {% set favCount = favCount + 1 %}#}
{#        {% endfor %}#}
{#        {% if favCount != 0 %}#}
        <a class="button is-info" href="{{ path('nomade_my_favorites') }}">
            Mes favoris
        </a>
{#        {% endif %}#}
    </div>


</div>




<div class="column" style="align-items: end;justify-content: end;display: flex;position: relative;">

    <div id="block-filtres" class="box" style="position: absolute;top: .75rem;z-index: 5;display: none;background: rgba(0,110,170,0.91)">

        {{ form_start(form) }}

        <label class="has-text-centered has-text-weight-bold column box" for="">
            <p class="subtitle">
                Loyer
            </p>

            <div class="control" style="margin: 0 .20rem">

                <div class="field has-addons" style="justify-content: center;">
                    <p class="control">
                        <a class="button is-static has-text-weight-normal">
                            Max
                        </a>
                    </p>
                    <div class="control">
                        {{ form_row(form.tarifMax) }}
                    </div>
                    <p class="control">
                        <a class="button is-static">
                            €
                        </a>
                    </p>
                </div>

                <div class="field has-addons" style="justify-content: center;">
                    <p class="control">
                        <a class="button is-static has-text-weight-normal">
                            Min
                        </a>
                    </p>
                    <div class="control">
                        {{ form_row(form.tarifMin) }}
                    </div>
                    <p class="control">
                        <a class="button is-static">
                            €
                        </a>
                    </p>
                </div>

            </div>
        </label>


        <label class="has-text-centered has-text-weight-bold column box" for="">

            <p class="subtitle">
                Superficie
            </p>

            <div class="control" style="margin: 0 .20rem">

                <div class="field has-addons" style="justify-content: center;">
                    <p class="control">
                        <a class="button is-static has-text-weight-normal">
                            Max
                        </a>
                    </p>
                    <div class="control">
                        {{ form_row(form.superficieMax) }}
                    </div>
                    <p class="control">
                        <a class="button is-static">
                            m²
                        </a>
                    </p>
                </div>

                <div class="field has-addons" style="justify-content: center;">
                    <p class="control">
                        <a class="button is-static has-text-weight-normal">
                            Min
                        </a>
                    </p>
                    <div class="control">
                        {{ form_row(form.superficieMin) }}
                    </div>
                    <p class="control">
                        <a class="button is-static">
                            m²
                        </a>
                    </p>
                </div>

            </div>
        </label>

        <div class="field has-addons column" style="justify-content: center">
            <p class="control">
                <button class="button is-info" type="submit">
                    Rechercher
                </button>
            </p>
        </div>

        {{ form_end(form) }}

    </div>



</div>

templates/includes/flash_message.html.twig
{# Affichage des messages flash #}
{% for type, message_list in app.flashes %}
    {% for message in message_list %}
        <div class="notification is-{{ type }}">
            <button class="delete" onclick="this.parentElement.parentElement.removeChild(this.parentElement);"></button>
            {{ message }}
        </div>
    {% endfor %}
{% endfor %}

templates/includes/footer_admin.html.twig
<footer class="footer has-background-success" style="position: relative;bottom:0 ;width: 100%;">

{#    <hr style="background: rgba(255,255,255,0.5);height: 2px;width: 95%;margin:auto;">#}

    <div class="content has-text-centered columns">

        <div class="column">
            <a class="is-link" href="{{ path('footer_contact') }}">Contact</a>
            <a class="is-link" href="{{ path('footer_cgu') }}">CGU/CGV</a>
            <a class="is-link" href="{{ path('footer_mentions') }}">Mentions légales</a>
        </div>


        <div class="column">
            <a class="is-link" href="{{ path('footer_pro') }}">Professionnels</a>
            <a class="is-link" href="{{ path('footer_partenariats') }}">Partenariats</a>
            <a class="is-link" href="{{ path('footer_annonceurs') }}">Annonceurs</a>
            <a class="is-link" href="{{ path('footer_presse') }}">Presse</a>
        </div>


        <div class="column">

            {#                <button class="button is-primary">#}
            {#                <span class="icon">#}
            {#                  <i class="fab fa-twitter"></i>#}
            {#                </span>#}
            {#                    <span><a href="https://twitter.com/MigMnty" target="_blank">Twitter</a></span>#}
            {#                </button>#}

            <span>
                        <a target="_blank" href="https://www.facebook.com/Qleaq.Officiel/">
                            <span class="icon">
                            <i class="fab fa-facebook"></i>
                            </span>Facebook
                        </a>
                    </span>

            {#                <button class="button is-primary">#}
            {#                <span class="icon">#}
            {#                  <i class="fab fa-youtube"></i>#}
            {#                </span>#}
            {#                    <span><a target="_blank" href="#">Youtube</a></span>#}
            {#                </button>#}

            <span><a  target="_blank"href="https://www.instagram.com/Qleaq_Officiel/">
                            <span class="icon">
                                <i class="fab fa-instagram"></i>
                            </span>Instagram
                        </a>
                    </span>



            <span><a  target="_blank"href="https://au.linkedin.com/company/qleaq-officiel">
                            <span class="icon">
                                <i class="fab fa-linkedin"></i>
                            </span>Linkedin
                        </a>
                    </span>

        </div>




    </div>


    <hr style="background: rgba(255,255,255,0.5);height: 1px;width: 100%;margin:auto;">

    <div class="column has-text-centered has-text-white">
        <span>
            © 2020 | www.qleaq.com [BETA] | Propriété de MEUNIETY Miguel. Tout droits réservés.
        </span>
    </div>


</footer>

templates/includes/footer_nomade.html.twig
<footer class="footer has-background-primary" style="position: relative;bottom:0 ;width: 100%;">

    <hr style="background: rgba(255,255,255,0.5);height: 2px;width: 95%;margin: 0 auto 50px auto;">

    <div class="content has-text-centered columns">

        <div class="column">
            <a class="is-link" href="{{ path('footer_contact') }}">Contact</a>
            <a class="is-link" href="{{ path('footer_cgu') }}">CGU/CGV</a>
            <a class="is-link" href="{{ path('footer_mentions') }}">Mentions légales</a>
        </div>


        <div class="column">
            <a class="is-link" href="{{ path('footer_pro') }}">Professionnels</a>
            <a class="is-link" href="{{ path('footer_partenariats') }}">Partenariats</a>
            <a class="is-link" href="{{ path('footer_annonceurs') }}">Annonceurs</a>
            <a class="is-link" href="{{ path('footer_presse') }}">Presse</a>
        </div>


        <div class="column">

            {#                <button class="button is-primary">#}
            {#                <span class="icon">#}
            {#                  <i class="fab fa-twitter"></i>#}
            {#                </span>#}
            {#                    <span><a href="https://twitter.com/MigMnty" target="_blank">Twitter</a></span>#}
            {#                </button>#}

            <span>
                        <a target="_blank" href="https://www.facebook.com/Qleaq.Officiel/">
                            <span class="icon">
                            <i class="fab fa-facebook"></i>
                            </span>Facebook
                        </a>
                    </span>

            {#                <button class="button is-primary">#}
            {#                <span class="icon">#}
            {#                  <i class="fab fa-youtube"></i>#}
            {#                </span>#}
            {#                    <span><a target="_blank" href="#">Youtube</a></span>#}
            {#                </button>#}

            <span><a  target="_blank"href="https://www.instagram.com/Qleaq_Officiel/">
                            <span class="icon">
                                <i class="fab fa-instagram"></i>
                            </span>Instagram
                        </a>
                    </span>



            <span><a  target="_blank"href="https://au.linkedin.com/company/qleaq-officiel">
                            <span class="icon">
                                <i class="fab fa-linkedin"></i>
                            </span>Linkedin
                        </a>
                    </span>

        </div>


    </div>
</footer>

templates/includes/footer_proprietaire.html.twig
<footer class="footer has-background-info" style="position: relative;bottom:0 ;width: 100%;">

{#    <hr style="background: rgba(255,255,255,0.5);height: 2px;width: 95%;margin:auto;">#}

    <div class="content has-text-centered columns">

        <div class="column">
            <a class="is-link" href="{{ path('footer_contact') }}">Contact</a>
            <a class="is-link" href="{{ path('footer_cgu') }}">CGU/CGV</a>
            <a class="is-link" href="{{ path('footer_mentions') }}">Mentions légales</a>
        </div>


        <div class="column">
            <a class="is-link" href="{{ path('footer_pro') }}">Professionnels</a>
            <a class="is-link" href="{{ path('footer_partenariats') }}">Partenariats</a>
            <a class="is-link" href="{{ path('footer_annonceurs') }}">Annonceurs</a>
            <a class="is-link" href="{{ path('footer_presse') }}">Presse</a>
        </div>


        <div class="column">

            {#                <button class="button is-primary">#}
            {#                <span class="icon">#}
            {#                  <i class="fab fa-twitter"></i>#}
            {#                </span>#}
            {#                    <span><a href="https://twitter.com/MigMnty" target="_blank">Twitter</a></span>#}
            {#                </button>#}

            <span>
                        <a target="_blank" href="https://www.facebook.com/Qleaq.Officiel/">
                            <span class="icon">
                            <i class="fab fa-facebook"></i>
                            </span>Facebook
                        </a>
                    </span>

            {#                <button class="button is-primary">#}
            {#                <span class="icon">#}
            {#                  <i class="fab fa-youtube"></i>#}
            {#                </span>#}
            {#                    <span><a target="_blank" href="#">Youtube</a></span>#}
            {#                </button>#}

            <span><a  target="_blank"href="https://www.instagram.com/Qleaq_Officiel/">
                            <span class="icon">
                                <i class="fab fa-instagram"></i>
                            </span>Instagram
                        </a>
                    </span>



            <span><a  target="_blank"href="https://au.linkedin.com/company/qleaq-officiel">
                            <span class="icon">
                                <i class="fab fa-linkedin"></i>
                            </span>Linkedin
                        </a>
                    </span>

        </div>




    </div>


    <hr style="background: rgba(255,255,255,0.5);height: 1px;width: 100%;margin:auto;">

    <div class="column has-text-centered has-text-white">
        <span>
            © 2020 | www.qleaq.com [BETA] | Propriété de MEUNIETY Miguel. Tout droits réservés.
        </span>
    </div>


</footer>

templates/includes/qleaq_title.html.twig
{% block qleaq %}
    QLEAQ |
{% endblock %}