src/Entity/Annonce.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\AnnonceRepository")
 * @UniqueEntity(fields={"titre"}, message="Ce titre d'annonce existe déjà, veuillez en choisir un autre.")
 * @Vich\Uploadable
 */
class Annonce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $illustration_name;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="illustrations", fileNameProperty="illustration_name")
     * @Assert\Image(
     *     maxSize="8Mi",
     *     mimeTypes={"image/jpeg", "image/png", "image/pdf"},
     *     mimeTypesMessage = "Seul les fichier jpg/jpeg/png/pdf sont acceptés")
     * )
     */
    private $illustration;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_logement;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_max_residents;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $superficie;

    /**
     * @ORM\Column(type="integer")
     */
    private $tarif;

    /**
     * @ORM\Column(type="date")
     */
    private $date_disponible;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

//    /**
//     * @ORM\ManyToOne(targetEntity="App\Entity\Proprietaire", inversedBy="annonces")
//     * @ORM\JoinColumn(nullable=false)
//     */
//    private $proprio;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $publicationAuth;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Proprietaire", inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $proprio;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $datePublication;

    /**
     * @ORM\ManyToMany(targetEntity=Nomade::class, mappedBy="favori")
     */
    private $nomades;

    public function __construct()
    {
        $this->date_creation = new \DateTime();
        $this->publicationAuth = false;
        $this->nomades = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTypeLogement(): ?string
    {
        return $this->type_logement;
    }

    public function setTypeLogement(string $type_logement): self
    {
        $this->type_logement = $type_logement;

        return $this;
    }

    public function getNombreMaxResidents(): ?int
    {
        return $this->nombre_max_residents;
    }

    public function setNombreMaxResidents(int $nombre_max_residents): self
    {
        $this->nombre_max_residents = $nombre_max_residents;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSuperficie(): ?float
    {
        return $this->superficie;
    }

    public function setSuperficie(float $superficie): self
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getTarif(): ?int
    {
        return $this->tarif;
    }

    public function setTarif(int $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getDateDisponible(): ?\DateTimeInterface
    {
        return $this->date_disponible;
    }

    public function setDateDisponible(\DateTimeInterface $date_disponible): self
    {
        $this->date_disponible = $date_disponible;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }



    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getPublicationAuth(): ?bool
    {
        return $this->publicationAuth;
    }

    public function setPublicationAuth(bool $publicationAuth): self
    {
        $this->publicationAuth = $publicationAuth;

        return $this;
    }

    public function getProprio(): ?Proprietaire
    {
        return $this->proprio;
    }

    public function setProprio(?Proprietaire $proprio): self
    {
        $this->proprio = $proprio;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->datePublication;
    }

    public function setDatePublication(?\DateTimeInterface $datePublication): self
    {
        $this->datePublication = $datePublication;

        return $this;
    }

    /**
     * @return Collection|Nomade[]
     */
    public function getNomades(): Collection
    {
        return $this->nomades;
    }

    public function addNomade(Nomade $nomade): self
    {
        if (!$this->nomades->contains($nomade)) {
            $this->nomades[] = $nomade;
            $nomade->addFavori($this);
        }

        return $this;
    }

    public function removeNomade(Nomade $nomade): self
    {
        if ($this->nomades->contains($nomade)) {
            $this->nomades->removeElement($nomade);
            $nomade->removeFavori($this);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getIllustrationName(): ?string
    {
        return $this->illustration_name;
    }

    /**
     * @param string|null $illustration_name
     * @return Annonce
     */
    public function setIllustrationName(?string $illustration_name): Annonce
    {
        $this->illustration_name = $illustration_name;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getIllustration(): ?File
    {
        return $this->illustration;
    }

    /**
     * @param File|null $illustration
     * @return Annonce
     */
    public function setIllustration(?File $illustration): Annonce
    {
        $this->illustration = $illustration;
        if ($this->illustration instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }



    //    public function getProprio(): ?Proprietaire
//    {
//        return $this->proprio;
//    }
//
//    public function setProprio(?Proprietaire $proprio): self
//    {
//        $this->proprio = $proprio;
//
//        return $this;
//    }





}

src/Entity/Proprietaire.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProprietaireRepository")
 * @UniqueEntity(fields={"email"}, message="L'email indiquée est déjà utilisée")
 * @ORM\HasLifecycleCallbacks()
 */
class Proprietaire implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $raison_social;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isConfirmed;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $securityToken;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation_compte;

    /**
     * @ORM\Column(type="integer")
     */
    private $refus = 0;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $refusToken;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Annonce", mappedBy="proprio", orphanRemoval=true)
     */
    private $annonces;

//    /**
//     * @ORM\OneToMany(targetEntity="App\Entity\Annonce", mappedBy="proprio")
//     */
//    private $annonces;




    public function __construct()
    {
        $this->date_creation_compte = new \DateTime();
//        $this->annonces = new ArrayCollection();
    }

    /**
     * Appelée lorsque l'objet est utilisé comme une chaine
     */
    public function __toString()
    {
        return $this->getUsername();
    }

    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
        // Si le statut isConfirmed n'est pas défini: mettre à false
        if ($this->isConfirmed === null) {
            $this->setIsConfirmed(false);
        }

//        if ($this->refus === null) {
//            $this->setRefus(false);
//        }

        // Définir un jeton s'il n'y en a pas
        if ($this->securityToken === null) {
            $this->renewToken();
        }

        if ($this->refusToken === null){
            $this->renewRefusToken();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSocial(): ?string
    {
        return $this->raison_social;
    }

    public function setRaisonSocial(string $raison_social): self
    {
        $this->raison_social = $raison_social;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_PROPRIO';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->raison_social;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getDateCreationCompte(): ?\DateTimeInterface
    {
        return $this->date_creation_compte;
    }

    public function setDateCreationCompte(\DateTimeInterface $date_creation_compte): self
    {
        $this->date_creation_compte = $date_creation_compte;

        return $this;
    }

    public function getIsConfirmed(): ?bool
    {
        return $this->isConfirmed;
    }

    public function setIsConfirmed(bool $isConfirmed): self
    {
        $this->isConfirmed = $isConfirmed;

        return $this;
    }

    public function getSecurityToken(): ?string
    {
        return $this->securityToken;
    }

    public function setSecurityToken(string $securityToken): self
    {
        $this->securityToken = $securityToken;

        return $this;
    }

    public function getRefusToken(): ?string
    {
        return $this->refusToken;
    }

    public function setRefusToken(string $refusToken): self
    {
        $this->refusToken = $refusToken;

        return $this;
    }

    public function getRefus()
    {
        return $this->refus;
    }

    public function setRefus(int $refus): self
    {
        $this->refus = $refus;

        return $this;
    }

    /**
     * Renouveller le jeton de sécurité
     */
    public function renewToken() : self
    {
        // Création d'un jeton
        $token = bin2hex(random_bytes(16));

        return $this->setSecurityToken($token);
    }

    public function renewRefusToken() : self
    {
        // Création d'un jeton
        $token = bin2hex(random_bytes(16));

        return $this->setRefusToken($token);
    }

    /**
     * @return Collection|Annonce[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setProprio($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->contains($annonce)) {
            $this->annonces->removeElement($annonce);
            // set the owning side to null (unless already changed)
            if ($annonce->getProprio() === $this) {
                $annonce->setProprio(null);
            }
        }

        return $this;
    }

//    /**
//     * @return Collection|Annonce[]
//     */
//    public function getAnnonces(): Collection
//    {
//        return $this->annonces;
//    }
//
//    public function addAnnonce(Annonce $annonce): self
//    {
//        if (!$this->annonces->contains($annonce)) {
//            $this->annonces[] = $annonce;
//            $annonce->setProprio($this);
//        }
//
//        return $this;
//    }

//    public function removeAnnonce(Annonce $annonce): self
//    {
//        if ($this->annonces->contains($annonce)) {
//            $this->annonces->removeElement($annonce);
//            // set the owning side to null (unless already changed)
//            if ($annonce->getProprio() === $this) {
//                $annonce->setProprio(null);
//            }
//        }
//
//        return $this;
//    }





}

templates/proprietaire/add_annonce.html.twig
{% extends 'header/index.html.twig' %}

{% block title %}{% include 'includes/qleaq_title.html.twig' %}Creation d'annonce{% endblock %}

{% block content %}
    <section>

        {% if is_granted('ROLE_PROPRIO') %}



            <section class="hero is-medium is-info is-bold">
                <div class="hero-body">
                    <div class="container">
                        <h1 class="title">
                            Espace de creation d'annonce
                        </h1>
{#                        <h2 class="subtitle">#}
{#                            Bienvenue sur votre espace Propriétaire#}
{#                        </h2>#}
                    </div>
                </div>
            </section>

            <section class="section">
                <a class="button is-info is-outlined" href="{{ path('proprio_home', {id: app.user.id} ) }}">
                    <strong>Retour</strong>
                </a>

                {#            <div class="navbar">#}
                {#                <div class="navbar-end"><a class="button is-info is-fullwidth" href="{{ path('proprio_home', {id: app.user.id} ) }}">#}
                {#                        <span>Mes Annonces</span>#}
                {#                    </a></div>#}
                {#            </div>#}


                <section class="section columns is-centered">



                    {{ form_start(annonceForm) }}


                    {% include 'includes/flash_message.html.twig' %}
                    {#                        {{ form_row(nomadeForm.nom, {'attr' : {'placeholder' : 'Entrez votre Nom'}#}
                    {#                        }) }}#}
                    {% if form_errors(annonceForm) != null %}
                        <div class="notification is-danger">
                            <button class="delete" onclick="this.parentElement.parentElement.removeChild(this.parentElement);"></button>
                            {{ form_errors(annonceForm) }}
                        </div>
                    {% endif %}




                    <div class="field">
                        <label class="label">Titre *</label>

                        <div class="" style="width: 100%;">

                            {{ form_row(annonceForm.titre, {'attr' : {'class' : 'select input', 'onkeyup' : 'verif_nombre_max(this, 25)', 'placeholder' : 'Entrez le titre de votre Annonce', 'alt' : 'titre'}
                            }) }}

                        </div>

                    </div>

                    <div class="field">
                        <label class="label">Type de logment </label>

                        <div class="select" style="width: 100%;">

                            {{ form_row(annonceForm.type_logement, {'attr' : {'class' : 'select input', 'placeholder' : 'Choisissez...', 'alt' : 'type logement'}
                            }) }}

                        </div>

                    </div>


                    <div class="field">
                        <label class="label">Nombre de résidents max</label>
                        <div class="select">
                            {{ form_row(annonceForm.nombre_max_residents, {'attr' : {'class' : 'input select', 'placeholder' : 'ex : Choisissez', 'alt' : 'nombre residents max'  }
                            }) }}
                        </div>
                    </div>




                    <div class="field">

                        <label class="label">Superficie (en m²)</label>

                        <div class="control">
                            {{ form_row(annonceForm.superficie, {'attr' : {'class' : 'input', 'placeholder' : 'ex : 45', 'onkeyup' : 'verif_nombre(this);verif_nombre_max(this, 3)' , 'alt' : 'superficie'  }
                            }) }}
                            {#                        <strong class=""> m²</strong>#}
                        </div>




                    </div>

                    <div class="field">

                        <label class="label">Tarif (en € / CC)</label>

                        <div class="control">

                            {{ form_row(annonceForm.tarif, {'attr' : {'class' : 'input', 'placeholder' : 'ex : 450', 'onkeyup' : 'verif_nombre(this);verif_nombre_max(this, 4);', 'alt' : 'tarif'  }
                            }) }}
                            {#                            <div class="">/ CC</div>#}

                        </div>

                    </div>

                    <div class="field">
                        <label class="label">Selectionnez la date de disponibilité du logement</label>

                        <div class="control">

                            <div class="select">{{ form_row( annonceForm.date_disponible.day, {'label' : ' ', 'attr' : {'class' : 'sel   '}} ) }}</div>
                            <div class="select">{{ form_row( annonceForm.date_disponible.month, {'label' : ' ', 'attr' : {'class' : 'select'}} ) }}</div>
                            <div class="select">{{ form_row( annonceForm.date_disponible.year, {'label' : ' ', 'attr' : {'class' : 'select'}} ) }}</div>

{#                            <input type="date">#}

                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Adresse</label>
                        <div class="control">
                            {{ form_row(annonceForm.adresse, {'attr' : {'class' : 'input', 'placeholder' : 'ex : 1 rue qleaq' , 'alt' : 'adresse'}
                            }) }}
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Code postale</label>
                        <div class="control">
                            {{ form_row(annonceForm.cp, {'attr' : {'class' : 'input', 'placeholder' : 'ex : 75000', 'pattern' : '[0-9]{5}' , 'onkeyup' : 'verif_nombre(this);verif_nombre_max(this, 5)', 'alt' : 'code postale'  }
                            }) }}
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Ville</label>
                        <div class="control">
                            {{ form_row(annonceForm.ville, {'attr' : {'class' : 'input', 'placeholder' : 'Entrez la ville' , 'alt' : 'ville'}
                            }) }}
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Illustration</label>

                        <div class="" style="width: 100%;">

                            {{ form_row(annonceForm.illustration, {'attr' : {'class' : 'image', 'alt' : 'images'}
                            }) }}

                        </div>
                        
                        {% if annonce.illustrationName %}
                            <img src="{{ vich_uploader_asset(annonce, 'illustration') | imagine_filter('thumb') }}" alt="">
                        {% endif %}

                    </div>


                    <div class="field">
                        <label class="label">Détails</label>

                        <div class="" style="width: 100%;">

                            {{ form_row(annonceForm.description, {'attr' : {'class' : 'textarea','rows' : 10 , 'onkeyup' : 'verif_nombre_max(this, 1000)', 'placeholder' : 'Entrez plus de détails ici ...', 'style' : 'resize:none;' , 'alt' : 'description'}
                            }) }}

                        </div>

                    </div>



                    <div class="column is-centered">
                        <button type="submit" style="width: 100%;" class="button is-success">Valider</button>
                    </div>




                    {{ form_end(annonceForm) }}



                </section>


                {% else %}

                    <section class="hero is-dark is-bold is-large">
                        <div class="hero-body">
                            <div class="container">
                                <h1 class="title">
                                    Vous n'êtes pas éligible à cette page
                                </h1>
                                <a class="button is-large" style="margin: auto" href="{{ path('header') }}">Revenir à l'Accueil</a>
                            </div>
                        </div>
                    </section>

                {% endif %}

            </section>


    </section>



{% endblock %}

templates/proprietaire/delete_annonce.html.twig
{% extends 'header/index.html.twig' %}

{% block title %}{% include 'includes/qleaq_title.html.twig' %}Suppression d'une annonce{% endblock %}

{% block content %}
    <section>

        {% if is_granted('ROLE_PROPRIO') %}

            <section class="hero is-medium is-success is-bold">
                <div class="hero-body">
                    <div class="container">

                        <h1 class="title is-1">
                            Suppression d'une annonce
                        </h1>
                        <hr>
                        <h2 class="subtitle">
                            Vous êtes sur le point de supprimer l'annonce : <div class="tag is-medium is-info">{{ annonce.titre }}</div>
                            <br>
                        </h2>

                    </div>
                </div>
            </section>



            <div class="notification is-warning  has-text-centered">
                <h2 class="title is-2" >Etes vous sur de vouloir supprimer l'annonce ?</h2>
                <i>(Irréversible)</i>
            </div>


            {% include('includes/target_delete.html.twig') %}









            <div class="columns is-centered section">

                <div class="column is-one-third">

                    <div class="field" >

                        {{ form_start(deleteAnnonceForm) }}

                        {% if annonce.publicationauth == null or annonce.publicationauth == false %}

                                <div class="column">
                                    <button type="submit" style="width: 100%;" class="button is-danger">Supprimer l'annonce</button>
                                </div>

                        {% elseif annonce.publicationauth == true %}

                            <div class="column">
                                <button class="button is-danger" id="open-modal" style="width: 100%;">Supprimer l'annonce</button>
                            </div>

                            <div class="modal">
                                <div class="modal-background"></div>
                                <div class="modal-card">

                                    <header class="modal-card-head has-background-warning">
                                        <p class="modal-card-title">Attention</p>
                                    </header>

                                    <section class="modal-card-body">
                                        L'annonce : <strong>{{ annonce.titre }}</strong> est actuellement <div class="tag is-success">publiée</div> . <br>
                                        Souhaitez vous tout de même la supprimer définitivement? <br>
                                        <i class="is-size-7">(ATTENTION : Cette action est irreverssible, l'annonce ne pourra être récupérée)</i>
                                    </section>

                                    <footer class="modal-card-foot" style="justify-content: space-between;">
                                        <button class="button close-popup">Annuler</button>
                                        <button class="button is-success">Confirmer</button>
                                    </footer>

                                </div>
                                <button class="modal-close is-large" aria-label="close">MODAL</button>
                            </div>

                        {% endif %}


                        <div class="column is-centered">
                            <a href="{{ path('proprio_home') }}" type="submit" style="width: 100%;" class="button is-success">Annuler</a>
                        </div>

                        {{ form_end(deleteAnnonceForm) }}




                    </div>
                </div>
            </div>

        {% else %}

            <section class="hero is-dark is-bold is-large">
                <div class="hero-body">
                    <div class="container">
                        <h1 class="title">
                            Vous n'êtes pas éligible à cette page
                        </h1>
                        <a class="button is-large" style="margin: auto" href="{{ path('header') }}">Revenir à l'Accueil</a>
                    </div>
                </div>
            </section>

        {% endif %}

    </section>



{% endblock %}

templates/proprietaire/lost_password.html.twig
{% extends 'header/index.html.twig' %}

{% block title %}
    {% include 'includes/qleaq_title.html.twig' %}Récupération de mot de passe
{% endblock %}

{% block content %}
    <div class="columns is-centered section">
        <div class="column is-half box">
            <h1 class="title has-text-primary has-text-centered">
                Mot de passe perdu
            </h1>

            {{ form_start(lost_proprio_password_form) }}


                <div class="field">

                    <label class="label">Email</label>

                    <div class="control">
                        {{ form_row(lost_proprio_password_form.email, {'attr' : {'class' : 'input', 'placeholder' : 'ex : mail@mail.com', 'alt' : 'email'}
                        }) }}
                    </div>

                </div>

            {% include 'includes/flash_message.html.twig' %}


            <button type="submit" class="button is-info is-fullwidth">
                Envoyer l'email de réinitialisation
            </button>

            {{ form_end(lost_proprio_password_form) }}








        </div>
    </div>
{% endblock %}